language: python

python:
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch

before_install:
  # Tricks to avoid tkinter error about X11:
  # 'no display name and no $DISPLAY environment variable'
  # http://docs.travis-ci.com/user/gui-and-headless-browsers/#Starting-a-Web-Server
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"

install:
  - pip install -r requirements.txt

os:
  - linux
  - osx

script:
  - python ./tests/fsm_test.py
  - python ./tests/Sender_test.py
